version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=true
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  extension:
    build:
      context: ./extension
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./extension:/app
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev